# pandas I/O

In [1]:
import pandas as pd
from pandas import DataFrame, Series

In [2]:
df = pd.read_clipboard()

In [3]:
df

    May 2020  May 2019  Change  Programming Language Ratings Change.1
0          1         2  change                     C  17.07%   +2.82%
1          2         1  change                  Java  16.28%   +0.28%
2          3         4  change                Python   9.12%   +1.29%
3          4         3  change                   C++   6.13%   -1.97%
4          5         6  change                    C#   4.29%   +0.30%
5          6         5  change          Visual Basic   4.18%   -1.01%
6          7         7     NaN            JavaScript   2.68%   -0.01%
7          8         9  change                   PHP   2.49%   -0.00%
8          9         8  change                   SQL   2.09%   -0.47%
9         10        21  change                     R   1.85%   +0.90%
10        11        18  change                 Swift   1.79%   +0.64%
11        12        19  change                    Go   1.27%   +0.15%
12        13        14  change                MATLAB   1.17%   -0.20%
13        14        10  change     Assembly language   1.12%   -0.69%
14        15        15     NaN                  Ruby   1.02%   -0.32%
15        16        20  change                PL/SQL   0.99%   -0.03%
16        17        16  change  Classic Visual Basic   0.89%   -0.43%
17        18        13  change                  Perl   0.88%   -0.51%
18        19        28  change               Scratch   0.83%   +0.32%
19        20        11  change           Objective-C   0.80%   -0.83%

In [8]:
df.to_json('Programming_Language.json')

In [12]:
df.to_html('Programming_Language.html', index=False)

In [10]:
df.to_csv('Programming_Language.csv')

In [11]:
!ls

array_1.npy  Numpy_array.ipynb	     pandas_series.ipynb
array.csv    Numpy_IO.ipynb	     Programming_Language.csv
array.txt    pandas_DataFrame.ipynb  Programming_Language.html
array_z.npz  Pandas_operation.ipynb  Programming_Language.json

In [14]:
pd.read_html('Programming_Language.html')

[    May 2020  May 2019  Change  Programming Language Ratings Change.1
 0          1         2  change                     C  17.07%   +2.82%
 1          2         1  change                  Java  16.28%   +0.28%
 2          3         4  change                Python   9.12%   +1.29%
 3          4         3  change                   C++   6.13%   -1.97%
 4          5         6  change                    C#   4.29%   +0.30%
 5          6         5  change          Visual Basic   4.18%   -1.01%
 6          7         7     NaN            JavaScript   2.68%   -0.01%
 7          8         9  change                   PHP   2.49%   -0.00%
 8          9         8  change                   SQL   2.09%   -0.47%
 9         10        21  change                     R   1.85%   +0.90%
 10        11        18  change                 Swift   1.79%   +0.64%
 11        12        19  change                    Go   1.27%   +0.15%
 12        13        14  change                MATLAB   1.17%   -0.20%
 13        14        10  change     Assembly language   1.12%   -0.69%
 14        15        15     NaN                  Ruby   1.02%   -0.32%
 15        16        20  change                PL/SQL   0.99%   -0.03%
 16        17        16  change  Classic Visual Basic   0.89%   -0.43%
 17        18        13  change                  Perl   0.88%   -0.51%
 18        19        28  change               Scratch   0.83%   +0.32%
 19        20        11  change           Objective-C   0.80%   -0.83%]

In [15]:
pd.read_json('Programming_Language.json')

    May 2020  May 2019  Change  Programming Language Ratings Change.1
0          1         2  change                     C  17.07%   +2.82%
1          2         1  change                  Java  16.28%   +0.28%
2          3         4  change                Python   9.12%   +1.29%
3          4         3  change                   C++   6.13%   -1.97%
4          5         6  change                    C#   4.29%   +0.30%
5          6         5  change          Visual Basic   4.18%   -1.01%
6          7         7    None            JavaScript   2.68%   -0.01%
7          8         9  change                   PHP   2.49%   -0.00%
8          9         8  change                   SQL   2.09%   -0.47%
9         10        21  change                     R   1.85%   +0.90%
10        11        18  change                 Swift   1.79%   +0.64%
11        12        19  change                    Go   1.27%   +0.15%
12        13        14  change                MATLAB   1.17%   -0.20%
13        14        10  change     Assembly language   1.12%   -0.69%
14        15        15    None                  Ruby   1.02%   -0.32%
15        16        20  change                PL/SQL   0.99%   -0.03%
16        17        16  change  Classic Visual Basic   0.89%   -0.43%
17        18        13  change                  Perl   0.88%   -0.51%
18        19        28  change               Scratch   0.83%   +0.32%
19        20        11  change           Objective-C   0.80%   -0.83%

# 数据清理

In [16]:
df

    May 2020  May 2019  Change  Programming Language Ratings Change.1
0          1         2  change                     C  17.07%   +2.82%
1          2         1  change                  Java  16.28%   +0.28%
2          3         4  change                Python   9.12%   +1.29%
3          4         3  change                   C++   6.13%   -1.97%
4          5         6  change                    C#   4.29%   +0.30%
5          6         5  change          Visual Basic   4.18%   -1.01%
6          7         7     NaN            JavaScript   2.68%   -0.01%
7          8         9  change                   PHP   2.49%   -0.00%
8          9         8  change                   SQL   2.09%   -0.47%
9         10        21  change                     R   1.85%   +0.90%
10        11        18  change                 Swift   1.79%   +0.64%
11        12        19  change                    Go   1.27%   +0.15%
12        13        14  change                MATLAB   1.17%   -0.20%
13        14        10  change     Assembly language   1.12%   -0.69%
14        15        15     NaN                  Ruby   1.02%   -0.32%
15        16        20  change                PL/SQL   0.99%   -0.03%
16        17        16  change  Classic Visual Basic   0.89%   -0.43%
17        18        13  change                  Perl   0.88%   -0.51%
18        19        28  change               Scratch   0.83%   +0.32%
19        20        11  change           Objective-C   0.80%   -0.83%

In [17]:
df.drop_duplicates('Change')

   May 2020  May 2019  Change Programming Language Ratings Change.1
0         1         2  change                    C  17.07%   +2.82%
6         7         7     NaN           JavaScript   2.68%   -0.01%

In [18]:
df.drop(columns='May 2019')

    May 2020  Change  Programming Language Ratings Change.1
0          1  change                     C  17.07%   +2.82%
1          2  change                  Java  16.28%   +0.28%
2          3  change                Python   9.12%   +1.29%
3          4  change                   C++   6.13%   -1.97%
4          5  change                    C#   4.29%   +0.30%
5          6  change          Visual Basic   4.18%   -1.01%
6          7     NaN            JavaScript   2.68%   -0.01%
7          8  change                   PHP   2.49%   -0.00%
8          9  change                   SQL   2.09%   -0.47%
9         10  change                     R   1.85%   +0.90%
10        11  change                 Swift   1.79%   +0.64%
11        12  change                    Go   1.27%   +0.15%
12        13  change                MATLAB   1.17%   -0.20%
13        14  change     Assembly language   1.12%   -0.69%
14        15     NaN                  Ruby   1.02%   -0.32%
15        16  change                PL/SQL   0.99%   -0.03%
16        17  change  Classic Visual Basic   0.89%   -0.43%
17        18  change                  Perl   0.88%   -0.51%
18        19  change               Scratch   0.83%   +0.32%
19        20  change           Objective-C   0.80%   -0.83%

In [19]:
df.drop(columns=['May 2019', 'Change'])

    May 2020  Programming Language Ratings Change.1
0          1                     C  17.07%   +2.82%
1          2                  Java  16.28%   +0.28%
2          3                Python   9.12%   +1.29%
3          4                   C++   6.13%   -1.97%
4          5                    C#   4.29%   +0.30%
5          6          Visual Basic   4.18%   -1.01%
6          7            JavaScript   2.68%   -0.01%
7          8                   PHP   2.49%   -0.00%
8          9                   SQL   2.09%   -0.47%
9         10                     R   1.85%   +0.90%
10        11                 Swift   1.79%   +0.64%
11        12                    Go   1.27%   +0.15%
12        13                MATLAB   1.17%   -0.20%
13        14     Assembly language   1.12%   -0.69%
14        15                  Ruby   1.02%   -0.32%
15        16                PL/SQL   0.99%   -0.03%
16        17  Classic Visual Basic   0.89%   -0.43%
17        18                  Perl   0.88%   -0.51%
18        19               Scratch   0.83%   +0.32%
19        20           Objective-C   0.80%   -0.83%

In [20]:
df.drop(index=[0, 1])

    May 2020  May 2019  Change  Programming Language Ratings Change.1
2          3         4  change                Python   9.12%   +1.29%
3          4         3  change                   C++   6.13%   -1.97%
4          5         6  change                    C#   4.29%   +0.30%
5          6         5  change          Visual Basic   4.18%   -1.01%
6          7         7     NaN            JavaScript   2.68%   -0.01%
7          8         9  change                   PHP   2.49%   -0.00%
8          9         8  change                   SQL   2.09%   -0.47%
9         10        21  change                     R   1.85%   +0.90%
10        11        18  change                 Swift   1.79%   +0.64%
11        12        19  change                    Go   1.27%   +0.15%
12        13        14  change                MATLAB   1.17%   -0.20%
13        14        10  change     Assembly language   1.12%   -0.69%
14        15        15     NaN                  Ruby   1.02%   -0.32%
15        16        20  change                PL/SQL   0.99%   -0.03%
16        17        16  change  Classic Visual Basic   0.89%   -0.43%
17        18        13  change                  Perl   0.88%   -0.51%
18        19        28  change               Scratch   0.83%   +0.32%
19        20        11  change           Objective-C   0.80%   -0.83%

In [34]:
df['May 2020'] = df['May 2020'].apply(lambda x:x-1)
df

    May 2020  May 2019  Change  Programming Language Ratings Change.1
0         -1         2  change                     C  17.07%   +2.82%
1          0         1  change                  Java  16.28%   +0.28%
2          1         4  change                Python   9.12%   +1.29%
3          2         3  change                   C++   6.13%   -1.97%
4          3         6  change                    C#   4.29%   +0.30%
5          4         5  change          Visual Basic   4.18%   -1.01%
6          5         7    None            JavaScript   2.68%   -0.01%
7          6         9  change                   PHP   2.49%   -0.00%
8          7         8  change                   SQL   2.09%   -0.47%
9          8        21  change                     R   1.85%   +0.90%
10         9        18  change                 Swift   1.79%   +0.64%
11        10        19  change                    Go   1.27%   +0.15%
12        11        14  change                MATLAB   1.17%   -0.20%
13        12        10  change     Assembly language   1.12%   -0.69%
14        13        15    None                  Ruby   1.02%   -0.32%
15        14        20  change                PL/SQL   0.99%   -0.03%
16        15        16  change  Classic Visual Basic   0.89%   -0.43%
17        16        13  change                  Perl   0.88%   -0.51%
18        17        28  change               Scratch   0.83%   +0.32%
19        18        11  change           Objective-C   0.80%   -0.83%